### ISSUE TITLE
Mousebites will generate emtpy board

### ISSUE THREAD

**Issue by fishjimi** [buganini/KiKit-UI#1]
![image](https://github.com/user-attachments/assets/af0688de-b6ac-4fe7-a5f7-7b25a3a257b7)

I have two different boards (same shape)
But it generate empty board if I chose Mousebites

![image](https://github.com/user-attachments/assets/a2d99d3e-b0cb-4980-9223-5aeeb35b3a14)

**Comment by buganini** [comment]
can you provide a pcb file with only the edge cuts?

it seems the edge is not in simple polygon, but it's covered by the red lines of debug view.

**Comment by fishjimi** [comment]
[edge_only.zip](https://github.com/user-attachments/files/17001597/edge_only.zip)
Please have a look
BTW, this project saved me !!
Thank you very much for your dedication

**Comment by fishjimi** [comment]
new problem found: Simulate Mill Fillets seems not working

**Comment by buganini** [comment]
Simulate Mill Fillets is only applied to preview, as the mill fillets should be part of actual milling.

But I can make it an option.

**Comment by buganini** [comment]
hmm it works here

<img width="1458" alt="image" src="https://github.com/user-attachments/assets/6d07d1c3-b444-45a9-8af7-8b20d26152d2">

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/864c6432-e9c7-4582-b947-3e3239f74c77">

**Comment by fishjimi** [comment]
really weird. Im using [kikit-ui-v2.1-windows-x64.zip](https://github.com/buganini/KiKit-UI/releases/download/2.1/kikit-ui-v2.1-windows-x64.zip)
and you can see the pictire I posted , the V-CUT lines(blue) still displaying when I chose Mousebites.
![image](https://github.com/user-attachments/assets/ed226294-7718-4ada-bbbd-60412f3b5bcd)

**Comment by buganini** [comment]
please try v2.2
