### ISSUE TITLE
Add pcb shows no *.kicad_pcb files

### ISSUE THREAD

**Issue by fishjimi** [buganini/KiKit-UI#2]
![image](https://github.com/user-attachments/assets/48cb0384-11d7-4cfb-a988-0852bd264b3a)

Add pcb shows no *.kicad_pcb files
But it can add PCB byI manually puting filename into dialog

**Comment by buganini** [comment]
are you using v2.0?
this should be fixed in v2.1
or you can type "*" in file name field as a quick workaround

**Comment by fishjimi** [comment]
Yes Im using v2.1
"*" does work

**Comment by buganini** [comment]
please try v2.2

**Comment by fishjimi** [comment]
Cool !!!
