### ISSUE TITLE
Renumber components to prevent duplicate designators

### ISSUE THREAD

**Issue by sdrgeek** [buganini/KiKit-UI#3]
Thank you very much for this tool, it helped me a lot! One thing I noticed tho was that the component designators aren't renumbered. In my multiboard panel are different parts with the same designator, which messes up the BOM and therefore makes PCB assembly difficult.

KiKit seems to already support this by adding `renameref `in the `layout` section. I wonder if you could implement this in your program.

TIA

**Comment by buganini** [comment]
implemented in b14b19e69b0416873b592f27e39214af236d9b3d

**Comment by buganini** [comment]
Please try https://github.com/buganini/KiKit-UI/releases/tag/3.0

**Comment by sdrgeek** [comment]
Works perfectly! Thank you very much for the fast implementation. Saved me a lot of work :)

**Comment by sdrgeek** [comment]
Noticed one issue: all component designators seem to be gone on silkscreen layer, except for the last board.

**Comment by buganini** [comment]
<img width="281" alt="image" src="https://github.com/user-attachments/assets/c2801048-068e-46f1-ab1e-c4196b6c1792">
try uncheck this

**Comment by sdrgeek** [comment]
thanks, that works. 

Is it supposed to remove everything except the silkscreen designators of the last pcb if this is checked tho?

**Comment by buganini** [comment]
It's because I sometimes have PCB with silkscreen  out of substrate like this, they are just ignored in single fabrication, but they overlap with other PCB in panelization.

<img width="681" alt="image" src="https://github.com/user-attachments/assets/44a569a8-e5b1-4a06-a943-c672f788e018">

**Comment by buganini** [comment]
yeah it's a bug and it's fixed in 640e26f88b61f256dd1b9600edd159e0cdd37dd2

probably not useful to be used with ref renamer
